### ISSUE TITLE
Translation to Portuguese (Help Wanted!)

### ISSUE THREAD

**Issue by loiane** [ng-girls/todo-list-tutorial-portuguese#1]
The following files need to be translated.

| File                            	| Status       	|
|-----------------------------------	|--------------	|
| README.md                         	| OK           	|
| SUMMARY.md                        	| OK           	|
| a_new_component.md                	| OK           	|
| add_items.md                      	| OK           	|
| add_more_abilities_to_service.md  	| OK           	|
| adding_a_checkbox.md              	| OK           	|
| adding_style.md                   	| OK           	|
| angular_kicks_in.md               	| OK           	|
| appendix-2-tutorial-extensions.md 	| OK           	|
| class.md                          	| OK 	|
| component.md                      	| OK      	|
| deploy_to_githubpages.md          	| OK 	|
| element_ref_-.md                  	| OK 	|
| enrich_the_todo-item_component.md 	| N/A          	|
| event_binding.md                  	| OK           	|
| generating_a_new_project.md       	| OK           	|
| installations.md                  	| OK           	|
| introduction.md                   	| OK           	|
| local_storage.md                  	| OK      	|
| new_component_todo-item.md        	| OK           	|
| property_binding.md               	| OK      	|
| refactor_app_component.md         	| OK           	|
| remove_item.md                    	| OK           	|
| service.md                        	| OK           	|
| the_list.md                       	| OK           	|

Please comment on this issue the file you will be translating. Once you translate it, please send a PR.

**Comment by bezzocoaline** [comment]
Hi Loiane, 
I translated the README file.

**Comment by mateusduraes** [comment]
Hello @loiane , i wll translate the ```remove_item.md``` file

**Comment by melostbr** [comment]
Hello @loiane, I've translated the `classes.md`: https://github.com/ng-girls/todo-list-tutorial-portuguese/pull/12

**Comment by alinebastos** [comment]
Hi, Loiane!
I will translate the `angular_kicks_in.md` file.

**Comment by joanasouza** [comment]
Hello @loiane can I pick localstorage.md file?

**Comment by cyz** [comment]
Hello @joanasouza and @alinebastos! 
Thank you for support us and please, go ahead to localize this files 👍 
Also, please, open an issue to register your localization :)

**Comment by raffaeldantass** [comment]
Hi @loiane! 
Can I pick component.md to translate?

**Comment by marcoribeirojr** [comment]
Hi @loiane!
The deploy_to_githubpages.md file is with me ok?! :wink:

**Comment by thaymara** [comment]
Hi @loiane I have translated deploy_to_githubpages and element_ref

**Comment by rosicleiafrasson** [comment]
Hi @loiane. I'll translate the_list.md

**Comment by cyz** [comment]
Hi @marcoribeirojr, this article was submitted by @thaymara and the PR already sent.

**Comment by loiane** [comment]
@raffaeldantass @thaymara @rosicleiafrasson ok! Thanks for helping!

**Comment by cyz** [comment]
@loiane the file enrich_the_todo-item_component.md is empty. I don't know if we need wait for content or can remove from the list.

**Comment by loiane** [comment]
@cyz marked as completed for now in case content is added to it in the future!

**Comment by cyz** [comment]
Team, I'll translate the file: generating_a_new_project.md

**Comment by maaryhabad** [comment]
I have translated the event_binding and sended a pull request :D

**Comment by dtgfranca** [comment]
Hi, Loiane!
I translate the file new_component_todo-item.md

**Comment by loiane** [comment]
@maaryhabad and @dtgfranca ok. Thanks for helping!

**Comment by pedrobarrostech** [comment]
Hi @loiane! I wil translate the property_binding.md

**Comment by renatacoelho** [comment]
Hi @loiane, I will translate the property_binding.md

**Comment by AlexandreKavalerski** [comment]
Hi @loiane ! I will translate the component.md

**Comment by loiane** [comment]
Hi all, we have 1 file pending: property_binding.md - who can help us with this file?

**Comment by AlexandreKavalerski** [comment]
I can translate it @loiane!

**Comment by hi-hi-ray** [comment]
@AlexandreKavalerski  are translating property_binding.md? =]

**Comment by loiane** [comment]
Hi all, all files translated! We are just waiting for 1 PR review!
We would like to thank all of you for the help!
