### ISSUE TITLE
Review Tutorial - Help Wanted

### ISSUE THREAD

**Issue by loiane** [ng-girls/todo-list-tutorial-portuguese#40]
Hi all, there are plans to run new ng-Girls workshops in Brazil.
Angular has been updated since last time this tutorial was reviewed and the original repo in English has also been updated.
We need help from the community to update the Portuguese version as well!

English repo: https://github.com/ng-girls/todo-list-tutorial
Please compare each file below to its original in English and if required, please send a PR.

The following files need to be reviewed:

| File                            	| Colaborator      	|Status |
|-----------------------------------	|--------------	| -------------|
| README.md                         	| @Kamilahsantos | **Done!**|
| SUMMARY.md                        	| @alvarocamillont | **Done!** |
| a_new_component.md                	| @brunagil |**Done!**|
| add-items-using-the-service.md   **(NEW)**                	| @AlexandreKavalerski           	|**Done!**|
| add_items.md                      	| @alvarocamillont           	|**Done!**|
| add_more_abilities_to_service.md (Removed)  	| @alvarocamillont  |**Done!**|
| adding_a_checkbox.md              	| @miohana           	|**Done!**|
| adding_style.md                   	| @brunagil |**Done!**|
| angular_kicks_in.md               	| @gabidombrowski |**Done!**|
|appendix-1-generating-a-new-project.md **(NEW)**   	| @marjoriernunes          	|**Done!**|
| appendix-2-tutorial-extensions.md 	| @marjoriernunes          	|**Done!**|
| class.md                          	| @alvarocamillont |**Done!**|
| component.md                      	| @OliveiraNadia|**Done!**|
| creating-a-service.md **(NEW)**  | @tapmorales       	|**Done!**|
| deploy_to_githubpages.md          	|  @jvaleskasilva |**Done!**|
| element_ref_-.md                  	| @Evelisee |**Done!**|
| enrich_the_todo-item_component.md 	|  @alvarocamillont |**Done!**|
| event_binding.md                  	| @elainemattos |**Done!**|
| generating_a_new_project.md       	| @marjoriernunes |**Done!**|
| interface.md (NEW) | @thaymara |**Done!**|
| installations.md                  	| @elainemattos            	|**Done!**|
| introduction.md                   	| @Kamilahsantos           	|**Done!**|
| local_storage.md                  	| @thaymara      	|**Done!**|
| new_component_todo-item.md        	| @elainemattos           	|**Done!**|
| property_binding.md               	| @eudivaloper|pending  |
| refactor_app_component.md         	| @marjoriernunes|**Done**|
| remove_item.md                    	| @cmatiello           	|**Done!**|
| service.md  (Removed)                  	| @alvarocamillont  |**Done!**|
| the_list.md                       	| @eudivaloper            	|**Done!**|

Please comment on this issue the file you will be translating/reviewing. Once you review it, please send a PR.

**Comment by alvarocneto** [comment]
Hi there!

I can help it too :)

**Comment by elainemattos** [comment]
Hey @loiane !
Can I help with  **installations.md**?

**Comment by tapmorales** [comment]
Hi, Can I review creating-a-service.md?

**Comment by Marinamontelo** [comment]
I can help with any file.

**Comment by alvarocneto** [comment]
I can help with SUMMARY.md too :)

**Comment by alvarocneto** [comment]
@loiane I think you need to add this items to the issues:

- interface.md (NEW)

**Comment by eudivaloper** [comment]
@loiane I can help with the_list.md?

**Comment by miohana** [comment]
Hi @loiane!

I can review adding-a-checkbox.md! 🎈

**Comment by gabidombrowski** [comment]
I can take adding_style.md!

**Comment by andre-lfa** [comment]
Hi @loiane, 

Can I help with class.md and angular-kicks-in.md?

**Comment by thaymara** [comment]
Hi @loiane !
I can help reviewing local_storage.md and translate interfaces.md if no one else is working on it.

**Comment by JulianoZanella** [comment]
Hi @loiane 
Can I translate the README.md?

**Comment by Kamilahsantos** [comment]
Hi @loiane ,
I sent the pull request from the introduction.md, can I help translate read.me?

**Comment by alvarocneto** [comment]
Hi @Kamilahsantos  I think @miohana  requested it first. 
@miohana are you already working on it?

Thanks!

**Comment by miohana** [comment]
Hi @alvarocneto! 

Now I'm working on the adding_a_checkbox.md.
@Kamilahsantos you can pick the readme.md, no problem! Will be a pleasure to have your help. I didn't started it yet.

**Comment by elainemattos** [comment]
Hi, can I help with "new_component_todo-item"?

**Comment by alvarocneto** [comment]
> 
> 
> Hi, can I help with "new_component_todo-item"?

It is yours! thk

**Comment by jvaleskasilva** [comment]
@loiane can I help with the 'deploy_to_githubpages.md'?

**Comment by Evelisee** [comment]
@loiane hey, can I help with the 'element_ref_-.md'? :)

**Comment by alvarocneto** [comment]
> 
> 
> @loiane can I help with the 'deploy_to_githubpages.md'?
It is yours! thk

**Comment by alvarocneto** [comment]
> 
> 
> @loiane hey, can I help with the 'element_ref_-.md'? :)

It is yours! thk

**Comment by psousaraquel** [comment]
Hi!, can I help with the 'enrich_the_todo-item_component.md'? :D

**Comment by alvarocneto** [comment]
> 
> 
> Hi!, can I help with the 'enrich_the_todo-item_component.md'? :D

It is yours! thk!

**Comment by alvarocneto** [comment]
Dont forget to put your name at README.md :)

**Comment by Kamilahsantos** [comment]
Hello, has anyone translated readme.md yet? If yes, can I translate property_binding.md?

**Comment by alvarocneto** [comment]
I think you did the readme...
Anyway I put your name  at Readme and property_binding.md
Thanks!

**Comment by marjoriernunes** [comment]
Hi!
Can I help with the generating_a_new_project.md? :)

**Comment by alvarocneto** [comment]
OK!
It is yours. Please don1t forget to put your name at Readme.md
Thk!

**Comment by marjoriernunes** [comment]
Hey!
I sent the pull request from the generating_a_new_project.md, can I help translate refactor_app_component.md? :)

**Comment by alvarocneto** [comment]
OF COURSE!
THANKS!

**Comment by elainemattos** [comment]
Hey, can I review event_binding.md?

**Comment by alvarocneto** [comment]
OK!
It is yours. 
Thk!

**Comment by marjoriernunes** [comment]
Hey!
Can I help with appendix-2-tutorial-extensions.md? :)

**Comment by alvarocneto** [comment]
OK!
It is yours.
Thk!

**Comment by alvarocneto** [comment]
Olá pessoal tudo bem?
Gostaríamos de finalizar essa issue então quem pegou algum documento para traduzir, caso não possa, não tem problemas, porém poderiam avisar aqui para atualizarmos o quadro de documentos.
@juunegreiros
@gabidombrowski
@andre-lfa
@anacunha
@Lukyhenson
@psousaraquel
@Kamilahsantos

Na semana que vem dia 7 eu vou liberar no quadro as tarefas que estão pendentes.
Novamente não tem problemas se vcs não conseguirem, apenas precisamos que avisem.

Grato!

**Comment by Kamilahsantos** [comment]
Olá, infelizmente não tive disponibilidade para traduzir o meu que estava pendente, se puder passar para outra pessoa =).
Obrigada e desculpe e a demora =)

**Comment by alvarocneto** [comment]
Sem problemas!

**Comment by anacunha** [comment]
> Olá pessoal tudo bem?
> Gostaríamos de finalizar essa issue então quem pegou algum documento para traduzir, caso não possa, não tem problemas, porém poderiam avisar aqui para atualizarmos o quadro de documentos.
> @juunegreiros
> @gabidombrowski
> @andre-lfa
> @anacunha
> @Lukyhenson
> @psousaraquel
> @Kamilahsantos
> 
> Na semana que vem dia 7 eu vou liberar no quadro as tarefas que estão pendentes.
> Novamente não tem problemas se vcs não conseguirem, apenas precisamos que avisem.
> 
> Grato!

Parece que a @marjoriernunes já fez a página `appendix-1-generating-a-new-project.md` que tinha ficado comigo.

**Comment by alvarocneto** [comment]
Me desculpe @anacunha . Gerenciar pelo comentario da issue pode ter suas falhas :)

**Comment by brunagil** [comment]
Oi gente! posso fazer o `a_new_component.md` e `adding_style.md`?

**Comment by OliveiraNadia** [comment]
Olá Pessoal! posso fazer esse 'component.md'?

**Comment by eudivaloper** [comment]
Oi, posso fazer property_binding.md?

**Comment by alvarocamillont** [comment]
Feito pessoa. Não esqueçam de colocar o seu nome no README

**Comment by alvarocamillont** [comment]
Boa noite @brunagil @OliveiraNadia @eudivaloper vocês irão fazer os itens que estão com vcs? Se não conseguirem não tem problema, apenas avisem que eu posso passar para outras pessoas :)
Grato!

**Comment by brunagil** [comment]
Oi @alvarocamillont, sim vou fazer o item!

**Comment by alvarocamillont** [comment]
Show!

**Comment by OliveiraNadia** [comment]
Olá @alvarocamillont , vou fazer o item sim.

**Comment by alvarocamillont** [comment]
Obrigado!

**Comment by OliveiraNadia** [comment]
Olá @alvarocamillont eu preciso de permissão para fazer um upload de uma imagem. Essa imagem consta na documentação original, e preciso subir para esse repositório para concluir minha tarefa. 

Essa é a imagem :  
https://raw.githubusercontent.com/ng-girls/todo-list-tutorial/master/.gitbook/assets/image.png

**Comment by OliveiraNadia** [comment]
@alvarocamillont  na verdade, eu preciso de permissão para dar um push.

**Comment by alvarocamillont** [comment]
Olá! @OliveiraNadia se vc subir a imagem no seu fork o pr atualiza para a master :)

**Comment by alvarocamillont** [comment]
Tenta subir o PR, pq eu acho que não tenho permissão de incluir vc :)

**Comment by OliveiraNadia** [comment]
Olá @alvarocamillont, mesmo subindo no meu fork, ele não atualiza na master. E quando tento subir na master, aparece esse erro:
![image](https://user-images.githubusercontent.com/8324846/63046135-39803f00-bea8-11e9-9f23-6b019b0e713d.png)

**Comment by alvarocamillont** [comment]
Na hora do PR ele incorpora  :) Sobe a imagem no seu fork e cria o PR para o nosso projeto.

Faz assim, termina a alteração e sobe seu pr.

Caso a imagem não apareça, a gente cria outro PR :)

**Comment by loiane** [comment]
@OliveiraNadia preciso comitar a imagem na sua branch e fazer um PR pra master. A gente não consegue fazer mudanças direto na master.

**Comment by OliveiraNadia** [comment]
Ahhh entendi. Obrigada @alvarocamillont  e @loiane  :)

**Comment by alvarocamillont** [comment]
Obrigado vc pela colaboração!
